import { contextBridge, ipcRenderer } from 'electron'
import { IPC, IPC_EVENTS } from '../src/constants'
import type {
  AiInstallEvent,
  AiSessionEvent,
  AppSettings,
  CatalogAnalysisProgress,
  DshMarketProgress,
  InstallProgress,
  GitHubPullRequestSummary,
  LauncherApi,
  LauncherUpdateProgress,
  PackProgressEvent,
  PluginTrialResult,
  RuntimeOutput,
  RuntimeState,
  WindowMode,
} from '../src/types'

/**
 * 渲染层与主进程之间唯一的桥。
 * 通道名来自共享常量，与主进程的注册面是同一份定义。
 */

/** 订阅一个主进程推送的事件，返回退订函数。 */
function subscribe<T>(channel: string, listener: (payload: T) => void): () => void {
  const wrapped = (_event: Electron.IpcRendererEvent, payload: T) => listener(payload)
  ipcRenderer.on(channel, wrapped)
  return () => ipcRenderer.removeListener(channel, wrapped)
}

const api: LauncherApi = {
  getSettings: () => ipcRenderer.invoke(IPC.settingsGet),
  saveSettings: (settings: AppSettings) => ipcRenderer.invoke(IPC.settingsSave, settings),
  detectDshInstallation: () => ipcRenderer.invoke(IPC.dshDetect),
  checkDshUpdate: () => ipcRenderer.invoke(IPC.dshUpdateCheck),
  readRuntimeEnvironment: refresh => ipcRenderer.invoke(IPC.runtimeEnvironmentRead, refresh),
  installDshVersion: version => ipcRenderer.invoke(IPC.runtimeEnvironmentInstallDsh, version),
  selectDshVersion: version => ipcRenderer.invoke(IPC.runtimeEnvironmentSelectDsh, version),
  removeDshVersion: version => ipcRenderer.invoke(IPC.runtimeEnvironmentRemoveDsh, version),
  installNodeVersion: version => ipcRenderer.invoke(IPC.runtimeEnvironmentInstallNode, version),
  selectNodeVersion: version => ipcRenderer.invoke(IPC.runtimeEnvironmentSelectNode, version),
  removeNodeVersion: version => ipcRenderer.invoke(IPC.runtimeEnvironmentRemoveNode, version),
  cancelRuntimeEnvironmentOperation: () => ipcRenderer.invoke(IPC.runtimeEnvironmentCancel),
  openDshFolder: () => ipcRenderer.invoke(IPC.runtimeEnvironmentOpenDshFolder),
  openNodeFolder: () => ipcRenderer.invoke(IPC.runtimeEnvironmentOpenNodeFolder),
  checkLauncherUpdate: () => ipcRenderer.invoke(IPC.launcherUpdateCheck),
  downloadLauncherUpdate: () => ipcRenderer.invoke(IPC.launcherUpdateDownload),
  applyLauncherUpdate: () => ipcRenderer.invoke(IPC.launcherUpdateApply),
  getDeepSeekCredentialStatus: () => ipcRenderer.invoke(IPC.credentialStatus),
  setDeepSeekApiKey: apiKey => ipcRenderer.invoke(IPC.credentialSet, apiKey),
  clearDeepSeekApiKey: () => ipcRenderer.invoke(IPC.credentialClear),
  listCustomApiProviders: () => ipcRenderer.invoke(IPC.customApiList),
  saveCustomApiProvider: input => ipcRenderer.invoke(IPC.customApiSave, input),
  removeCustomApiProvider: route => ipcRenderer.invoke(IPC.customApiRemove, route),
  getGitHubAuthStatus: () => ipcRenderer.invoke(IPC.githubAuthStatus),
  loginGitHubWithToken: token => ipcRenderer.invoke(IPC.githubAuthTokenLogin, token),
  beginGitHubDeviceLogin: () => ipcRenderer.invoke(IPC.githubAuthDeviceBegin),
  completeGitHubDeviceLogin: () => ipcRenderer.invoke(IPC.githubAuthDeviceComplete),
  cancelGitHubDeviceLogin: () => ipcRenderer.invoke(IPC.githubAuthDeviceCancel),
  logoutGitHub: () => ipcRenderer.invoke(IPC.githubAuthLogout),
  listGitHubPullRequests: () => ipcRenderer.invoke(IPC.githubPullRequests) as Promise<GitHubPullRequestSummary[]>,
  getGitHubStarStatus: repository => ipcRenderer.invoke(IPC.githubStarStatus, repository),
  setGitHubStar: (repository, starred) => ipcRenderer.invoke(IPC.githubStarSet, { repository, starred }),
  chooseDirectory: kind => ipcRenderer.invoke(IPC.chooseDirectory, kind),
  readProfile: () => ipcRenderer.invoke(IPC.profileRead),
  listProfiles: () => ipcRenderer.invoke(IPC.profilesList),
  createProfile: request => ipcRenderer.invoke(IPC.profilesCreate, request),
  cloneProfile: (sourceName, targetName, description) => ipcRenderer.invoke(IPC.profilesClone, { sourceName, targetName, description }),
  switchProfile: (profileName, options) => ipcRenderer.invoke(IPC.profilesSwitch, { profileName, fillMissing: options?.fillMissing === true }),
  deleteProfile: profileName => ipcRenderer.invoke(IPC.profilesDelete, profileName),
  readProfileMetadata: profileName => ipcRenderer.invoke(IPC.profilesMetadata, profileName),
  exportProfile: (profileName, mode, options) => ipcRenderer.invoke(IPC.profilesExport, { profileName, mode, ...options }),
  importProfile: (filePath, options) => ipcRenderer.invoke(IPC.profilesImport, { filePath, name: options?.name, overwrite: options?.overwrite === true }),
  analyzeProfileRepository: url => ipcRenderer.invoke(IPC.profilesRepositoryAnalyze, url),
  importProfileRepository: (url, options) => ipcRenderer.invoke(IPC.profilesRepositoryImport, { url, mode: options.mode, name: options.name, overwrite: options.overwrite === true, resolutions: options.resolutions }),
  matchProfilePlugin: packageName => ipcRenderer.invoke(IPC.profilesMatchPlugin, packageName),
  togglePlugin: (packageName, enabled) => ipcRenderer.invoke(IPC.profileToggle, { packageName, enabled }),
  reorderPlugins: packageNames => ipcRenderer.invoke(IPC.profileReorder, packageNames),
  discoverCatalog: (query, sort, page) => ipcRenderer.invoke(IPC.catalogDiscover, { query, sort, page }),
  refreshCatalogIndex: () => ipcRenderer.invoke(IPC.catalogRefreshIndex),
  analyzeCatalogRepository: (fullName, defaultBranch, repositoryUpdatedAt) => ipcRenderer.invoke(IPC.catalogAnalyze, { fullName, defaultBranch, repositoryUpdatedAt }),
  importCatalogUrl: url => ipcRenderer.invoke(IPC.catalogImportUrl, { url }),
  loadDshMarket: () => ipcRenderer.invoke(IPC.dshMarketLoad),
  installDshMarketPlugin: name => ipcRenderer.invoke(IPC.dshMarketInstall, name),
  updateDshMarketPlugin: name => ipcRenderer.invoke(IPC.dshMarketUpdate, name),
  uninstallDshMarketPlugin: name => ipcRenderer.invoke(IPC.dshMarketUninstall, name),
  toggleDshMarketPlugin: (name, enabled) => ipcRenderer.invoke(IPC.dshMarketToggle, { name, enabled }),
  checkDshMarketUpdates: force => ipcRenderer.invoke(IPC.dshMarketUpdates, force),
  installPlugin: request => ipcRenderer.invoke(IPC.pluginsInstall, request),
  uninstallPlugin: packageName => ipcRenderer.invoke(IPC.pluginsUninstall, packageName),
  trialPlugin: (packageName, profileName) => ipcRenderer.invoke(IPC.pluginsTrial, { packageName, profileName }),
  readPluginTrials: () => ipcRenderer.invoke(IPC.pluginsTrialRead),
  installSkill: request => ipcRenderer.invoke(IPC.skillsInstall, request),
  readInstalledSkills: () => ipcRenderer.invoke(IPC.skillsReadInstalled),
  toggleSkill: (name, enabled) => ipcRenderer.invoke(IPC.skillsToggle, { name, enabled }),
  installApplication: request => ipcRenderer.invoke(IPC.applicationsInstall, request),
  readInstalledApplications: () => ipcRenderer.invoke(IPC.applicationsReadInstalled),
  toggleApplication: (id, enabled) => ipcRenderer.invoke(IPC.applicationsToggle, { id, enabled }),
  uninstallApplication: id => ipcRenderer.invoke(IPC.applicationsUninstall, id),
  installPreset: request => ipcRenderer.invoke(IPC.presetsInstall, request),
  readInstalledPresets: () => ipcRenderer.invoke(IPC.presetsReadInstalled),
  togglePreset: (name, enabled) => ipcRenderer.invoke(IPC.presetsToggle, { name, enabled }),
  getRuntimeState: () => ipcRenderer.invoke(IPC.runtimeState),
  startRuntime: () => ipcRenderer.invoke(IPC.runtimeStart),
  stopRuntime: () => ipcRenderer.invoke(IPC.runtimeStop),
  openExternal: url => ipcRenderer.invoke(IPC.openExternal, url),
  openPath: path => ipcRenderer.invoke(IPC.openPath, path),
  setWindowMode: (mode: WindowMode) => ipcRenderer.invoke(IPC.windowSetMode, mode),
  minimizeWindow: () => ipcRenderer.invoke(IPC.windowMinimize),
  toggleMaximizeWindow: () => ipcRenderer.invoke(IPC.windowToggleMaximize),
  closeWindow: () => ipcRenderer.invoke(IPC.windowClose),
  aiInstall: input => ipcRenderer.invoke(IPC.aiInstall, input),
  aiAdaptPlugin: input => ipcRenderer.invoke(IPC.aiAdaptPlugin, input),
  aiRepairRuntime: () => ipcRenderer.invoke(IPC.aiRepairRuntime),
  aiApprove: (requestId, allow) => ipcRenderer.invoke(IPC.aiApprove, requestId, allow),
  aiCancel: () => ipcRenderer.invoke(IPC.aiCancel),
  aiRollback: () => ipcRenderer.invoke(IPC.aiRollback),
  aiStatus: () => ipcRenderer.invoke(IPC.aiStatus),
  aiHasSnapshot: () => ipcRenderer.invoke(IPC.aiHasSnapshot),
  listAiSessions: () => ipcRenderer.invoke(IPC.aiSessionsList),
  createAiSession: input => ipcRenderer.invoke(IPC.aiSessionsCreate, input),
  sendAiSessionMessage: (sessionId, text) => ipcRenderer.invoke(IPC.aiSessionsSend, { sessionId, text }),
  cancelAiSession: sessionId => ipcRenderer.invoke(IPC.aiSessionsCancel, sessionId),
  approveAiSession: (sessionId, requestId, allow) => ipcRenderer.invoke(IPC.aiSessionsApprove, { sessionId, requestId, allow }),
  rollbackAiSession: sessionId => ipcRenderer.invoke(IPC.aiSessionsRollback, sessionId),
  deleteAiSession: sessionId => ipcRenderer.invoke(IPC.aiSessionsDelete, sessionId),
  listPacks: () => ipcRenderer.invoke(IPC.packsList),
  createPack: request => ipcRenderer.invoke(IPC.packsCreate, request),
  analyzePackImport: path => ipcRenderer.invoke(IPC.packsAnalyzeImport, path),
  importPack: (path, items, options) => ipcRenderer.invoke(IPC.packsImport, path, items, options?.name),
  exportPack: packId => ipcRenderer.invoke(IPC.packsExport, packId),
  pickPackFile: () => ipcRenderer.invoke(IPC.packsPickFile),
  activatePack: packId => ipcRenderer.invoke(IPC.packsActivate, packId),
  deactivatePack: () => ipcRenderer.invoke(IPC.packsDeactivate),
  removePack: packId => ipcRenderer.invoke(IPC.packsRemove, packId),
  rollbackPack: () => ipcRenderer.invoke(IPC.packsRollback),
  packHasSnapshot: () => ipcRenderer.invoke(IPC.packsHasSnapshot),
  addPackPlugin: (packId, packageName) => ipcRenderer.invoke(IPC.packsAddPlugin, { packId, packageName }),
  addPackPreset: (packId, presetName) => ipcRenderer.invoke(IPC.packsAddPreset, { packId, presetName }),
  addPackSkill: (packId, skillName) => ipcRenderer.invoke(IPC.packsAddSkill, { packId, skillName }),
  addPackApplication: (packId, addonId) => ipcRenderer.invoke(IPC.packsAddApplication, { packId, addonId }),
  togglePackItem: (packId, packageName, enabled) => ipcRenderer.invoke(IPC.packsToggleItem, { packId, packageName, enabled }),
  togglePackPreset: (packId, presetName, enabled) => ipcRenderer.invoke(IPC.packsTogglePreset, { packId, presetName, enabled }),
  togglePackSkill: (packId, skillName, enabled) => ipcRenderer.invoke(IPC.packsToggleSkill, { packId, skillName, enabled }),
  togglePackApplication: (packId, addonId, enabled) => ipcRenderer.invoke(IPC.packsToggleApplication, { packId, addonId, enabled }),
  removePackItem: (packId, packageName) => ipcRenderer.invoke(IPC.packsRemoveItem, { packId, packageName }),
  removePackPreset: (packId, presetName) => ipcRenderer.invoke(IPC.packsRemovePreset, { packId, presetName }),
  removePackSkill: (packId, skillName) => ipcRenderer.invoke(IPC.packsRemoveSkill, { packId, skillName }),
  removePackApplication: (packId, addonId) => ipcRenderer.invoke(IPC.packsRemoveApplication, { packId, addonId }),
  onCatalogAnalysisProgress: listener => subscribe<CatalogAnalysisProgress>(IPC_EVENTS.catalogAnalysisProgress, listener),
  onDshMarketProgress: listener => subscribe<DshMarketProgress>(IPC_EVENTS.dshMarketProgress, listener),
  onPackProgress: listener => subscribe<PackProgressEvent>(IPC_EVENTS.packProgress, listener),
  onRuntimeOutput: listener => subscribe<RuntimeOutput>(IPC_EVENTS.runtimeOutput, listener),
  onRuntimeState: listener => subscribe<RuntimeState>(IPC_EVENTS.runtimeStateChanged, listener),
  onInstallProgress: listener => subscribe<InstallProgress>(IPC_EVENTS.installProgress, listener),
  onLauncherUpdateProgress: listener => subscribe<LauncherUpdateProgress>(IPC_EVENTS.launcherUpdateProgress, listener),
  onPluginTrialEvent: listener => subscribe<PluginTrialResult>(IPC_EVENTS.pluginTrialEvent, listener),
  onAiInstallEvent: listener => subscribe<AiInstallEvent>(IPC_EVENTS.aiInstallEvent, listener),
  onAiSessionEvent: listener => subscribe<AiSessionEvent>(IPC_EVENTS.aiSessionEvent, listener),
}

contextBridge.exposeInMainWorld('launcher', api)
